modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="ore_fish"
version="1.0.0"
displayName="Ore Fish"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="isaac, MCreator"

[[dependencies.ore_fish]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




